### ISSUE TITLE
When can one expect a new build?

### ISSUE THREAD

**Issue by VikramDave** [75lb/grunt-yuidoc2md#4]
I am using this project to generate markdown files and was wondering if you could provide a rough estimate of when this project will be available again. 

Thanks.

**Comment by 75lb** [comment]
hi, i have published the module back to npm.. it can be accessed again now.. i'm currently focussed on finishing the https://github.com/75lb/jsdoc-to-markdown which uses the superior jsdoc3.. would you consider a switch from yuidoc to jsdoc?

**Comment by VikramDave** [comment]
Thanks for publishing back to npm. I will be open to switching from switch from yuidoc to jsdoc, if it is stable and can generate Javascript API docs markdown files from javascript files. I chose grunt-yuidoc2md because I can generate API docs for constructors which other can't. I will try it out once it is ready. Do you have rough time span by which it will be ready? Are you planning to close this repo and have only on https://github.com/75lb/jsdoc-to-markdown?  Taking off of npm affected my builds so am trying to have a fall back strategy.  What should one do in case you take down this repo?

**Comment by 75lb** [comment]
don't worry, it won't get taken down again.. i was led to believe the project was broken, so felt talking it down was the responsible thing to do (whilst i am not maintaining it, at least).. i will have preview releases of jsdoc-to-markdown up in the next few days, will let you know.. once that has stabilised i will update yuidoc2md too (it will essentially become a separate data source feeding into the same, shared generator)..

**Comment by VikramDave** [comment]
Great, I will stay tuned. What kind of features it has? Is there a spec or something I can look at?

**Comment by 75lb** [comment]
this project is now deprecated, superceded by https://github.com/75lb/jsdoc-to-markdown
